services:
  - type: web
    name: mapa-de-gols-oficial
    env: python
    buildCommand: "pip install --upgrade pip"
    startCommand: "python server.py"
    envVars:
      - key: PORT
        value: 10000
