const POSICOES={"lateral-esquerdo":"laterais-esquerdos","lateral-direito":"laterais-direitos",meia:"meias",volante:"volantes","ponta-esquerda":"pontas pelo lado esquerdo","ponta-direita":"pontas pelo lado direito","atacante-area":"atacantes de área"};
const NOMES={"red-bull-bragantino":"Red Bull Bragantino","atletico-mg":"Atlético-MG","athletico-pr":"Athletico-PR","sao-paulo":"São Paulo",gremio:"Grêmio",vitoria:"Vitória"};
const time=s=>NOMES[s]||String(s).split("-").map(p=>p[0].toUpperCase()+p.slice(1)).join(" ");
const cap=s=>s?s[0].toUpperCase()+s.slice(1):s;
const num=n=>n.toLocaleString("pt-BR",{maximumFractionDigits:1});
function lista(xs){return xs.length<2?(xs[0]||""):xs.length===2?`${xs[0]} e ${xs[1]}`:`${xs.slice(0,-1).join(", ")} e ${xs.at(-1)}`}
function padrao(d,c){if(d==="area")return c==="dentro-da-area"?"finalizações de dentro da área":"finalizações de fora da área";if(d==="parteDoCorpo"&&c==="cabeca")return"finalizações de cabeça";if(d==="contraAtaque")return"finalizações em contra-ataques";if(d==="ladoDaJogada")return`finalizações em jogadas construídas pelo lado ${c==="esquerda"?"esquerdo":"direito"}`;const o={CRUZAMENTO:"finalizações após cruzamentos",ESCANTEIO:"finalizações após escanteios",FALTA:"finalizações após cobranças de falta",LANCAMENTO:"finalizações após lançamentos longos",REBATIDA:"finalizações após sobras de bola"};return d==="origem"?o[c]||null:null}
function entradas(m){const r=[];for(const[t,is]of m||[])for(const i of is||[])if(i?.achado&&i?.frase&&i.achado.distintividade?.direcao==="alto")r.push({time:t,...i});return r}
function grupo(xs,chave){const m=new Map;for(const x of xs){const k=chave(x);if(!k)continue;if(!m.has(k))m.set(k,[]);m.get(k).push(x)}const media=a=>a.reduce((n,x)=>n+(x.achado.distintividade?.valor||0),0)/a.length;return[...m].sort((a,b)=>b[1].length-a[1].length||media(b[1])-media(a[1]))[0]||null}
const top=xs=>[...xs].sort((a,b)=>(b.achado.porJogo||0)-(a.achado.porJogo||0))[0];
function posicao(xs,p,defesa){const melhor=top(xs),nomes=lista(xs.map(x=>time(x.time))),valor=num(melhor.achado.porJogo);return defesa?`${cap(POSICOES[p])} adversários finalizam acima do normal contra ${nomes}. O alerta é mais forte no ${time(melhor.time)}, que permite cerca de ${valor} finalizações por jogo a essa posição. Na prática, essa é uma rota clara para observar nos adversários dessas defesas.`:`${cap(POSICOES[p])} concentram uma parcela acima do normal das finalizações de ${nomes}. O caso mais forte é o ${time(melhor.time)}, com cerca de ${valor} finalizações por jogo nessa posição. Na prática, vale acompanhar esses jogadores como as principais referências de chute dessas equipes.`}
function recorrente(xs,n,defesa){const melhor=top(xs),nomes=lista(xs.map(x=>time(x.time))),valor=num(melhor.achado.porJogo);return defesa?`${cap(n)} aparecem acima do normal contra ${nomes}. O caso mais forte é o ${time(melhor.time)}, que cede cerca de ${valor} finalizações por jogo dessa forma. Na prática, os adversários encontram nessa jogada uma maneira recorrente de ameaçar essas defesas.`:`${cap(n)} aparecem acima do normal nos ataques de ${nomes}. O caso mais forte é o ${time(melhor.time)}, com cerca de ${valor} finalizações por jogo dessa forma. Na prática, essa jogada mostra como essas equipes costumam construir suas chances.`}
function destaqueDefensivo(m){const e=[...(m||new Map)].filter(([,x])=>Number.isFinite(x?.finalizacoesCedidasPorJogo)&&x.jogosUsados>=5).sort((a,b)=>a[1].finalizacoesCedidasPorJogo-b[1].finalizacoesCedidasPorJogo).slice(0,3);if(e.length<2)return null;const[l,...d]=e,resto=d.map(x=>`${time(x[0])} (${num(x[1].finalizacoesCedidasPorJogo)} por jogo)`);return{tipo:"destaque-defensivo",frase:`${time(l[0])} apresenta o melhor controle defensivo da amostra: permite cerca de ${num(l[1].finalizacoesCedidasPorJogo)} finalizações por jogo. ${lista(resto)} também estão entre as defesas que menos permitem chutes. Na prática, são as equipes que mais reduzem o volume ofensivo dos adversários.`,times:e.map(([t])=>t)}}
export function gerarResumoRodada({ofensivosPorTime,defensivosPorTime,metricasDefensivasPorTime,rodada=null,janelaAte=null,geradoEm=new Date().toISOString()}={}){const o=entradas(ofensivosPorTime),d=entradas(defensivosPorTime),conclusoes=[];const po=grupo(o.filter(x=>x.achado.dimensao==="posicao"),x=>x.achado.categoria);if(po&&POSICOES[po[0]])conclusoes.push({tipo:"posicao-ofensiva",frase:posicao(po[1],po[0],false),times:po[1].map(x=>x.time)});const dd=destaqueDefensivo(metricasDefensivasPorTime);if(dd)conclusoes.push(dd);const pd=grupo(d.filter(x=>x.achado.dimensao==="posicao"),x=>x.achado.categoria);if(pd&&POSICOES[pd[0]])conclusoes.push({tipo:"alvo-defensivo",frase:posicao(pd[1],pd[0],true),times:pd[1].map(x=>x.time)});for(const[tipo,xs,def]of[["padrao-ofensivo",o,false],["fragilidade-recorrente",d,true]]){const g=grupo(xs.filter(x=>padrao(x.achado.dimensao,x.achado.categoria)),x=>`${x.achado.dimensao}|${x.achado.categoria}`);if(g){const[k,casos]=g,[dim,...cat]=k.split("|");conclusoes.push({tipo,frase:recorrente(casos,padrao(dim,cat.join("|")),def),times:casos.map(x=>x.time)})}}return{versao:2,rodada,janelaAte,geradoEm,conclusoes}}
